### ISSUE TITLE
Error while training model

### ISSUE THREAD

**Issue by xibalbanus** [byucsl/ogcleaner#2]
G'day,

First of all I would like to thank you for such a useful program. I have been able to run with using the pre-trained models without any issues. However, when I try training with my own selection of OrthoDB groups I get the following error:

python ~/apps/ogcleaner/bin/ogcleaner.py train --orthodb_fasta crustacea.universal.single.fasta --threads 10 --clean
Command: /home/vader/apps/ogcleaner/bin/ogcleaner.py train --orthodb_fasta crustacea.universal.single.fasta --threads 10 --clean
OrthoClean model training module version 0.1a
Aligner: /home/vader/apps/ogcleaner/lib/mafft_bin/mafft
Aligner args: --anysymbol
Created directory train_orthodb_groups_fasta
Created directory train_nh_groups_fasta
Created directory train_paml_configs
Created directory logs
Created directory train_cluster_alignments_homology
Created directory train_cluster_alignments_nh
Created directory train_paml_trees
Created directory train_evolved_seqs
Created directory train_featurized_clusters
Created directory train_aliscores_homology
Created directory train_aliscores_nh
Beginning...
	**Segregating the sequences into their orthogroups...Traceback (most recent call last):
  File "/home/vader/apps/ogcleaner/bin/ogcleaner.py", line 1750, in <module>
    main( args )
  File "/home/vader/apps/ogcleaner/bin/ogcleaner.py", line 1426, in main
    generate_trained_model( args )
  File "/home/vader/apps/ogcleaner/bin/ogcleaner.py", line 1190, in generate_trained_model
    ortho_groups = segregate_orthodb_groups( args.orthodb_fasta, args.orthodb_groups_dir, args.og_field_pos )
  File "/home/vader/apps/ogcleaner/bin/ogcleaner.py", line 294, in segregate_orthodb_groups
    t_group = m.group( 1 )
AttributeError: 'NoneType' object has no attribute 'group'**

Any ideas about how to solve this?

Thanks in advance,

J.

EDIT: I fixed this (shown below) but I ran into a new error...

**Comment by xibalbanus** [comment]
If it helps, this is what the fasta file looks like: 

>294128:002b15 "pub_gene_id":"HAZT011030", "pub_og_id":"EOG090Y0000", "og_name":"actin binding","level":6657
LAQYASSLGDAAHGLEERVRLWRDYEATYERILRWMGEAEASLRDFCSRNSLQQKQEQLDKYQLVFASRHALVVEFCSIADKLEQNLICSMNQHQGDLEQLTNDSCDLM

(sequence truncated for sake of post)

Maybe the header changed from previous versions?

**Comment by masakistan** [comment]
Hey, so sorry for the late reply. I hadn't set my personal github account to 'watching' so I missed this. I apologize for that.

If it would still be helpful for you, I'd love to help.

Could you tell me how you got your OrthoDB groups? From what I can tell you grabbed from Crustacea with the Phyloprofile `Present in all species` and `Single-copy in all species`.

Let me know if this is correct and I can try running it on my end to see what I come up with.
